spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: stock-public
          uri: lb://stock-service
          predicates:
            - Path=/api/v1/stock/**
        
        - id: stock-data-internal
          uri: lb://stock-data
          predicates:
            - Path=/internal/stock-data/**
            - Header=X-Internal-Request, true
          filters:
            - StripPrefix=1

        - id: health-check
          uri: lb://stock-data
          predicates:
            - Path=/actuator/health
          filters:
            - name: Retry
              args:
                retries: 2

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://your-frontend-domain.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      default-filters:
        - name: AddRequestHeader
          args:
            name: X-Gateway-Request
            value: "true"
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/auth/realms/your-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.yanosik.rcd: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    gateway:
      access: read_only
